version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    platform: linux/amd64
    environment:
      NODE_ENV: production
    volumes:
      - ./server/data:/app/data

  client:
    build: ./client
    ports:
      - "5173:5173"
